company:
  name: "Fake Company"
  business_id: "0000000-0"
software: "investment-softa"
service_provider_id: "spid"
account_period: "2025-03-01:2026-02-28"
input_dir: "/home/rui/Documents/company_data/tiliote/extracted"
output_dir: "output "


