spring.application.name=investment
server.error.include-message=always
spring.jpa.properties.jakarta.persistence.jdbc.url=jdbc:h2:mem:testdb
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=drop-and-create
spring.jpa.properties.jakarta.persistence.sql-load-script-source=classpath:insert_companies.sql
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
