INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'AES', 'AES', 'AES Corp');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'AMR', 'AMR', 'Alpha Metallurgical Resources Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'MO', 'MO', 'Altria Group Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'T', 'T', 'AT&T Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'BNTX', 'BNTX US', 'Biontech SE ADR');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'BRSL', 'BRSL', 'Brightstar Lottery PLC');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'BMY', 'BMY', 'Bristol-Myers Squibb Co');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'BATS.L', 'BATS', 'British American Tobacco');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'BTI', 'BTI', 'British American Tobacco ADR');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'CVX', 'CVX', 'Chevron');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'STZ', 'STZ.N', 'Constellation Brands Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'CVS', 'CVS', 'CVS Health Corp');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'DAC', 'DAC', 'Danaos');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'EOAN.DE', 'EOAN', 'E.ON N');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'ENB', 'ENB', 'Enbridge');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'XOM', 'XOM', 'Exxon Mobil Corp');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'FIA1S.HE', 'FIA1S', 'Finnair Oyj');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'FORTUM.HE', 'FORTUM', 'Fortum Oyj');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'GIS', 'GIS US', 'General Mills Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'GILD', 'GILD', 'Gilead Sciences, Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'GSK.L', 'GSK', 'GlaxoSmithKline');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'IMB.L', 'IMB', 'Imperial Brands');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'JD', 'JD', 'JD.com Inc A ADR');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'KHC', 'KHC', 'Kraft Heinz Co');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'MANTA.HE', 'MANTA', 'Mandatum');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'MRK', 'MRK', 'Merck & Co Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'MRNA', 'MRNA', 'Moderna Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'NE', 'NE', 'Noble Corp PLC');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'NOVO-B.CO', 'NOVO B', 'Novo Nordisk B');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'OXY', 'OXY US', 'Occidental Petroleum Corp');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'PLTR', 'PLTR', 'Palantir Technologies Inc A');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'PDD', 'PDD US', 'PDD Holdings Inc ADR');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'PFE', 'PFE US', 'Pfizer Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'PM', 'PM', 'Philip Morris International Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'SAGCV.HE', 'SAGCV', 'Saga Furs Oyj');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'SAMPO.HE', 'SAMPO', 'Sampo Oyj A');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'SIRI', 'SIRI', 'Sirius XM Holdings Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'T.TO', 'T CN', 'Telus');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'TCEHY', 'TCEHY', 'Tencent Holdings Ltd.');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'UNH', 'UNH US', 'UnitedHealth Group Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'USB', 'USB', 'US Bancorp');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'VZ', 'VZ US', 'Verizon Communications Inc');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'VOD.L', 'VOD', 'Vodafone Group');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'VODI', 'VODI', 'Vodafone Group PLC');
INSERT INTO company (id, yahoo_symbol, op_symbol, name) VALUES (NEXT VALUE FOR company_id_seq, 'HCC', 'HCC', 'Warrior Met Coal Inc');
